name: Bug
description: For general issues that don't fit into another category
title: "Short description of the bug"
labels: bug

body:
  - type: textarea
    id: bugdesc
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce / Cause of the issue
      description: Tell us how we can reproduce the issue / fix this issue
      placeholder: |
        1. Go to ...  
        2. Click on ...  
        3. Scroll down to ...  
        4. See error
    validations:
      required: true
  - type: input
    id: expectedBehaviour
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
